### ISSUE TITLE
Google Chrome Android freeze

### ISSUE THREAD

**Issue by wobility** [richardcornish/jquery-geolocate#2]
When the geolocation authorization request pop-up appears, it is not possible on Google Chrome to click on authorize or block. I have a OnePlus 7 Pro phone with the latest version of Google Chrome.

Have you ever encountered this problem or any idea how to fix it?

**Comment by richardcornish** [comment]
I've never encountered the problem. It sounds like it would be an issue with Google Chrome rather than the plugin. The plugin simply uses the existing HTML5 geolocation API, and it's up to the browser to ask the user permission and to make sure that dialogue window works.

If you try other websites that use HTML5 geolocation, can you still authorize or block?

**Comment by wobility** [comment]
Thanks for your replay. After some tests the problem come from some android device and some other app like Facebook messenger ( https://www.androidpolice.com/2019/11/01/psa-chrome-confirmation-buttons-on-android-10-overlay/ ) But I don't know why my device not working, Google chrome or android bug may be... Thanks for your time and good work !
